blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Contribution Guide
    url: https://v2.egytech.fyi/community/contribute
    about: Check the guide if you want to contribute to this project.
  - name: âœï¸ Participate to the Survey
    url: https://v2.egytech.fyi/community/participate
    about: Share your data with the community to help making a better tech scene in Egypt.
